---
sudo: required
language: ruby
services:
  - docker
matrix:
  include:
  - rvm: default
    env: BEAKER_set="debian-7_docker"
  - rvm: default
    env: BEAKER_set="debian-8_docker"
  - rvm: default
    env: BEAKER_set="centos-5_docker"
  - rvm: default
    env: BEAKER_set="centos-6_docker"
  - rvm: default
    env: BEAKER_set="centos-7_docker"
script: 'bundle exec rspec spec/acceptance'
notifications:
  email: false