---
sudo: required
language: ruby
cache: bundler
script: "bundle exec rake validate lint spec"
matrix:
  include:
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=docker/centos-5
    script: bundle exec rake beaker
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=docker/centos-6
    script: bundle exec rake beaker
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=docker/centos-7
    script: bundle exec rake beaker
notifications:
  email: false