---
sudo: required
language: ruby
services:
  - docker
matrix:
  include:
  - rvm: default
    env: BEAKER_set="debian-7"
  - rvm: default
    env: BEAKER_set="debian-8"
  - rvm: default
    env: BEAKER_set="centos-5"
  - rvm: default
    env: BEAKER_set="centos-6"
  - rvm: default
    env: BEAKER_set="centos-7"
script: 'bundle exec spec spec/acceptance'
notifications:
  email: false